{{- if .Values.image.tab }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "az-device-shop-factory.fullname" . }}
  labels:
    {{- include "az-device-shop-factory.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "az-device-shop-factory.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "az-device-shop-factory.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ default "" .Values.global.registryHost }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USE_COSMOS
              value: "true"
            - name: STORAGE_ACCOUNT
              value: {{ required "env.STORAGE_ACCOUNT Value required" .Values.global.env.STORAGE_ACCOUNT | quote}}
            - name: STORAGE_CONTAINER
              value: {{ required "env.STORAGE_CONTAINER Value required" .Values.global.env.STORAGE_CONTAINER | quote}}
            - name: STORAGE_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "az-device-shop-factory.fullname" . }}
                  key: STORAGE_MASTER_KEY
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "az-device-shop-factory.fullname" . }}
                  key: MONGO_DB
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}