{{- if .Values.ingress.enabled -}}
{{- $ingressDomain  := .Values.az-device-shop-web.ingressDomain -}}
{{- $ingressHost  := .Values.az-device-shop-web.ingressHost -}}
{{- $fullName := include "az-device-shop-web.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $factoryService := printf "%s-%s" $.Release.Name "az-device-shop-factory" | trunc 63 | trimSuffix "-" }}
{{- $orderingService := printf "%s-%s" $.Release.Name "az-device-shop-ordering" | trunc 63 | trimSuffix "-" }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "az-device-shop-web.labels" . | nindent 4 }}
  annotations:
    #  kubernetes.io/ingress.class: contour
    projectcontour.io/websocket-routes: "/ws/factory/,/ws/ordering/"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ $ingressHost }}.{{ $ingressDomain }}"
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: "{{ $ingressHost }}.{{ $ingressDomain }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port:
                name: http
        - path: /ws/factory/
          pathType: Prefix
          backend:
            service:
              name: {{ $factoryService }}
              port:
                name: http
        - path: /ws/ordering/
          pathType: Prefix
          backend:
            service:
              name: {{ $orderingService }}
              port:
                name: http
  {{- end }}
