apiVersion: v1
kind: Secret
metadata:
  name: {{ include "az-device-shop-web.fullname" . }}
  labels:
    {{- include "az-device-shop-web.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB: {{ required "env.MONGO_DB Value required" .Values.global.env.MONGO_DB | b64enc | quote }}
  B2C_CLIENT_SECRET: {{ required "env.B2C_CLIENT_SECRET Value required" .Values.env.B2C_CLIENT_SECRET | b64enc | quote }}
  STORAGE_MASTER_KEY: {{ required "env.STORAGE_MASTER_KEY Value required" .Values.global.env.STORAGE_MASTER_KEY | b64enc | quote }}

