{{- if .Values.image.tab }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "az-device-shop-ordering.fullname" . }}
  labels:
    {{- include "az-device-shop-ordering.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_DB: {{ required "env.MONGO_DB Value required" .Values.global.env.MONGO_DB | b64enc | quote }}
  STORAGE_MASTER_KEY: {{ required "env.STORAGE_MASTER_KEY Value required" .Values.global.env.STORAGE_MASTER_KEY | b64enc | quote }}
{{- end -}}
