name: Deploy AKS-Construction

on:
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/reusable.yml@main
    with:
      rg: az-k8s-ha0x-rg
      resourceName: az-k8s-ha0x
      upgradeChannel: stable
      agentCountMax: 20
      custom_vnet: true
      enable_aad: true
      AksDisableLocalAccounts: true
      enableAzureRBAC: true
      registries_sku: Premium
      omsagent: true
      retentionInDays: 30
      networkPolicy: azure
      azurepolicy: audit
      authorizedIPRanges: "[\"5.67.72.204/32\"]"
      ingressApplicationGateway: true
      appGWcount: 0
      appGWsku: WAF_v2
      appGWmaxCount: 10
      appgwKVIntegration: true
      azureKeyvaultSecretsProvider: true
      createKV: true

    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
