name: Deploy AKS-Construction

on:
  workflow_dispatch:
    inputs:
      username:
        required: false
        type: string

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/reusable.yml@kh-postdeploy
    with:
      rg: az-k8s-4soj-rg
      resourceName: az-k8s-4soj
      agentCount: 2
      upgradeChannel: stable
      JustUseSystemPool: true
      custom_vnet: true
      CreateNetworkSecurityGroups: true
      enable_aad: true
      AksDisableLocalAccounts: true
      enableAzureRBAC: true
      registries_sku: Basic
      azurepolicy: audit
      dnsZoneId: /subscriptions/95efa97a-9b5d-4f74-9f75-a3396e23344d/resourceGroups/kh-common/providers/Microsoft.Network/dnszones/labhome.biz
      azureKeyvaultSecretsProvider: true
      createKV: true
    secrets:
      AZURE_CLIENT_ID: f1beb0ec-f9d6-4a33-aa4a-0999e7f4572f
      AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
      AZURE_SUBSCRIPTION_ID: 95efa97a-9b5d-4f74-9f75-a3396e23344d
