name: deploy
on: [push, workflow_dispatch]
env:
  REGISTRY_NAME: khcommon
  CLUSTER_NAME: az-k8s-9137
  CLUSTER_RESOURCE_GROUP: az-k8s-9137-rg
  NAMESPACE: az-shop
  APP_NAME: az-shop

jobs:
  helm-deploy:
    environment: labhome.biz
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: web-tag

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      # Create namespace if doesn't exist
      - run: |
          tag=`cat output/web-tag.txt`
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
          helm upgrade ${{ env.APP_NAME }} ./helm/az-device-shop --reuse-values -n ${{ env.NAMESPACE }} \
            --set az-device-shop-web.image.tag=$tag
