name: Full End-2-End integration test
on:
  workflow_dispatch:
    inputs:
      mongoVersion:
        description: 'Mongo Version'     
        required: true
        default: '4.0'
env:
  AZURITE_ACCOUNT: "devstoreaccount1"
  AZURITE_MASTER_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
  STORAGE_CONTAINER: "az-shop-images"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ github.event.inputs.mongoVersion }}
        mongodb-replica-set: rs0
    
    - name: Microservices build
      run: |
        npm -g install npm@latest
        sh ./workflows/dev.1.build.sh

    - name: Microservices Launch
      timeout-minutes: 1
      env:
        STORAGE_ACCOUNT: ${{ env.AZURITE_ACCOUNT }}
        STORAGE_MASTER_KEY: ${{ env.AZURITE_MASTER_KEY }}
        STORAGE_CONTAINER: ${{ env.STORAGE_CONTAINER }}
        MONGO_DB: "mongodb://localhost:27017/dbdev?replicaSet=rs0"
        USE_COSMOS: "false"
      run: |
        
        # Mkdir for `azurite` storage local emulator
        mkdir ./__blobstorage__
        # Start azurity only
        npx pm2 start ./pm2.config.js --only blob
        # Wait for azurite to launch, then create container
        sleep 2
        AZURE_STORAGE_CONNECTION_STRING="UseDevelopmentStorage=true" az storage container create -n az-shop-images

        # Start everything
        npx pm2 start ./pm2.config.js

        # Print logs
        npx pm2 logs --nostream

    - name: Playwright End-to-End

      run: |
        npx playwright test
    
 