name: Integration Test
on:
  workflow_dispatch:
    inputs:
      mongoVersion:
        description: 'Mongo Version'     
        required: true
        default: '4.0'
env:
  AZURITE_ACCOUNT: "devstoreaccount1"
  AZURITE_MASTER_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
  STORAGE_CONTAINER: "az-shop-images"

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    # Feature: https://github.community/t/any-ways-to-pass-arguments-to-service-containers/16826/2
    #services:
    #  azurite:
    #    image: mcr.microsoft.com/azure-storage/azurite
    #    ports:
    #      - 10000:10000
    #    options: --entrypoint azurite-blob 
    #    args: --blobHost 0.0.0.0 --blobPort 10000

    steps:
    - uses: actions/checkout@main
    
    - name: Create Azure Storage Container
      run: |
        # https://mcr.microsoft.com/v2/azure-storage/azurite/tags/list (why not a actions service)
        # https://github.com/Azure/Azurite/issues/676 (--loose)
        AZURITE_CONTAINER=$(docker create  -p 10000:10000 --entrypoint azurite-blob -e GITHUB_ACTIONS=true -e CI=true mcr.microsoft.com/azure-storage/azurite:3.15.0 --blobHost 0.0.0.0 --blobPort 10000 --loose)
        docker start $AZURITE_CONTAINER
        sleep 2
        az storage container create -n ${{ env.STORAGE_CONTAINER }} --connection-string "DefaultEndpointsProtocol=http;AccountName=${{ env.AZURITE_ACCOUNT }};AccountKey=${{ env.AZURITE_MASTER_KEY }};BlobEndpoint=http://localhost:10000/${{ env.AZURITE_ACCOUNT }};"

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ github.event.inputs.mongoVersion }}
        mongodb-replica-set: rs0
    

    - name: Build
      run: |
        npm -g install npm@latest
        sh ./workflows/dev.1.build.sh

    - name: Run
      timeout-minutes: 1
      env:
        STORAGE_ACCOUNT: ${{ env.AZURITE_ACCOUNT }}
        STORAGE_MASTER_KEY: ${{ env.AZURITE_MASTER_KEY }}
        STORAGE_CONTAINER: ${{ env.STORAGE_CONTAINER }}
        MONGO_DB: "mongodb://localhost:27017/dbdev?replicaSet=rs0"
        USE_COSMOS: "false"
      run: |
        
        # Mkdir for `azurite` storage local emulator
        mkdir ./__blobstorage__
        # Start azurity only
        npx pm2 start blob
        # Wait for azurite to launch, then create container
        sleep 2
        AZURE_STORAGE_CONNECTION_STRING="UseDevelopmentStorage=true" az storage container create -n az-shop-images

        # Start everything
        npx pm2 start ./pm2.config.js

    - name: Test

      run: |
        npx playwright test
    
 