name: Local Test
on:
  workflow_dispatch:
    inputs:
      mongoVersion:
        description: 'Mongo Version'     
        required: true
        default: '4.0'
env:
  AZURITE_ACCOUNT: "devstoreaccount1"
  AZURITE_MASTER_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
  STORAGE_CONTAINER: "az-shop-images"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Start Azure Storage Emulation
      uses: addnab/docker-run-action@v3
      with:
        registry: mcr.microsoft.com
        image: azure-storage/azurite
        options: -p 10000:10000 azurite-blob
        run: |
          # docker run -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob
          az storage container create -n ${{ env.STORAGE_CONTAINER }} --connection-string "DefaultEndpointsProtocol=http;AccountName=${{ env.AZURITE_ACCOUNT }};AccountKey=${{ env.AZURITE_MASTER_KEY }};BlobEndpoint=http://127.0.0.1:10000/${{ env.AZURITE_ACCOUNT }};"
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ github.event.inputs.mongoVersion }}
        mongodb-replica-set: rs0
    
    - name: Build
      run: |

        npm -g install npm@latest
        npm i

        echo "Build Eventing.."
        cd common/eventing
        #npm i
        npm run build

        echo "Build Factory.."
        cd ../../factory 
        #npm i
        npm run build

        echo "Build Ordering.."
        cd ../ordering
        #npm i
        npm run build

        echo "Build Web.."
        cd ../web/web-react
        #npm i --legacy-peer-deps
        npm run-script build_lib
        npm run-script build_assets_prod

        cd ../web-server
        #npm i 
        npm run build


    - name: Run
      env:
        REACT_APP_FACTORY_PORT: "9091"
        REACT_APP_ORDERING_PORT: "9090"
        STORAGE_ACCOUNT: ${{ env.AZURITE_ACCOUNT }}
        STORAGE_MASTER_KEY: ${{ env.AZURITE_MASTER_KEY }}
        STORAGE_CONTAINER: ${{ env.STORAGE_CONTAINER }}
        MONGO_DB: "mongodb://localhost:27017/dbdev?replicaSet=rs0"
        USE_COSMOS: "true"

      run: |
        cd ./web
        PORT=30001 NODE_PATH=../node_modules node ./web-server/lib/server.js 
 
    - name: Test

      run: |
        curl localhost:30001
    
 