name: DEPRICATED Build and Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
#  push:
#    paths:
#      - "web/**"
#      - "common/**"
#      - "factory/**"
#      - "ordering/**"
env:
  REGISTRY_NAME: khcommon
  CLUSTER_NAME: az-k8s-9137
  CLUSTER_RESOURCE_GROUP: az-k8s-9137-rg
  NAMESPACE: az-shop
  APP_NAME: az-shop

jobs:
  build-web:
    environment: labhome.biz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Docker Registory Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Container build and push to a Azure Container registry (ACR)
      - name: Build and Push Web
        working-directory: ./web
        run: |
          docker build ../ -t ${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/web:${{ github.sha }} -f Dockerfile.root 
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/web:${{ github.sha }}

      - shell: bash
        run: |
          echo "${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/web:${{ github.sha }}" > web-tag.txt

      - name: Upload Docker Tag Web
        uses: actions/upload-artifact@v2
        with:
          name: web-tag
          path: web-tag.txt

      - name: Build and Push factory
        working-directory: ./factory
        run: |
          docker build ../ -t ${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/factory:${{ github.sha }} -f Dockerfile.root 
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/factory:${{ github.sha }}

      - shell: bash
        run: |
          echo "${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/factory:${{ github.sha }}" > factory-tag.txt

      - name: Upload Docker Tag Factory
        uses: actions/upload-artifact@v2
        with:
          name: factory-tag
          path: factory-tag.txt

      - name: Build and Push ordering
        working-directory: ./ordering
        run: |
          docker build ../ -t ${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/ordering:${{ github.sha }} -f Dockerfile.root 
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/ordering:${{ github.sha }}

      - shell: bash
        run: |
          echo "${{ env.REGISTRY_NAME }}.azurecr.io/az-device-shop/ordering:${{ github.sha }}" > ordering-tag.txt

      - name: Upload Docker Tag Ordering
        uses: actions/upload-artifact@v2
        with:
          name: ordering-tag
          path: ordering-tag.txt

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
          helm upgrade ${{ env.APP_NAME }} ./helm/az-device-shop --reuse-values -n ${{ env.NAMESPACE }} \
            --set az-device-shop-web.image.tag=${{ github.sha }} \
            --set az-device-shop-factory.image.tag=${{ github.sha }} \
            --set az-device-shop-ordering.image.tag=${{ github.sha }}
