on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string
      deploy_target:
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        env:
          inputs_json: "${{ toJSON(inputs) }}"
        run: |
          echo "$inputs_json"
