name: reusable


on:
  workflow_call:
    inputs:
      templateVersion:
        description: 'Template Version'
        required: false
        default: '0.8.5-preview'
        type: string
      rg:
        description: 'ResourceGroup name'
        required: true
        type: string
      resourceName:
        description: 'Unique name all your resources are based on'
        required: true
        type: string
      kubernetesVersion:
        description: 'kubernetesVersion'
        required: false
        type: string
      agentCount:
        description: 'agentCount'
        required: false
        default: 2
        type: number
      upgradeChannel:
        description: 'upgradeChannel'
        required: false
        type: string
      AksPaidSkuForSLA:
        description: 'AksPaidSkuForSLA'
        required: false
        type: boolean
        default: false
      JustUseSystemPool:
        description: 'Use a single nodepool for system and user workloads'
        required: false
        type: boolean
        default: false
      SystemPoolType:
        description: 'SystemPoolType'
        required: false
        type: string
      agentVMSize:
        description: 'agentVMSize'
        required: false
        type: string
      agentCountMax:
        description: 'Used for autoscale if greater than agent count'
        required: false
        default: 0
        type: number
      osDiskType:
        description: 'osDiskType'
        required: false
        type: string
      osDiskSizeGB:
        description: 'osDiskSizeGB'
        required: false
        type: number
      custom_vnet:
        description: 'Create a custom VNET'
        required: false
        default: false
        type: boolean
      CreateNetworkSecurityGroups:
        description: 'CreateNetworkSecurityGroups'
        required: false
        default: false
        type: boolean
      CreateNetworkSecurityGroupFlowLogs:
        description: 'CreateNetworkSecurityGroupFlowLogs'
        required: false
        default: false
        type: boolean
      bastion:
        description: 'bastion'
        required: false
        default: false
        type: boolean
      bastionSubnetAddressPrefix:
        description: 'bastionSubnetAddressPrefix'
        required: false
        type: string
      enable_aad:
        description: 'enable_aad'
        required: false
        default: false
        type: boolean
      AksDisableLocalAccounts:
        description: 'AksDisableLocalAccounts'
        required: false
        default: false
        type: boolean
      enableAzureRBAC:
        description: 'enableAzureRBAC'
        required: false
        default: false
        type: boolean
      adminPrincipalId:
        description: 'adminPrincipalId'
        required: false
        type: string
      registries_sku:
        description: 'registries_sku'
        required: false
        type: string
      acrPushRolePrincipalId:
        description: 'acrPushRolePrincipalId'
        required: false
        type: string
      imageNames:
        description: 'imageNames'
        required: false
        default: '[]'
        type: string
      azureFirewalls:
        description: 'azureFirewalls'
        required: false
        default: false
        type: boolean
      privateLinks:
        description: 'privateLinks'
        required: false
        default: false
        type: boolean
      omsagent:
        description: 'omsagent'
        required: false
        default: false
        type: boolean
      createAksMetricAlerts:
        description: 'createAksMetricAlerts'
        required: false
        default: false
        type: boolean
      networkPolicy:
        description: 'networkPolicy'
        required: false
        type: string
      azurepolicy:
        description: 'azurepolicy'
        required: false
        type: string
      networkPlugin:
        description: 'networkPlugin'
        required: false
        type: string
      availabilityZones:
        description: 'availabilityZones'
        required: false
        default: '[]'
        type: string
      authorizedIPRanges:
        description: 'authorizedIPRanges'
        required: false
        default: '[]'
        type: string
      enablePrivateCluster:
        description: 'enablePrivateCluster'
        required: false
        default: false
        type: boolean
      dnsZoneId:
        description: 'dnsZoneId'
        required: false
        type: string
      ingressApplicationGateway:
        description: 'ingressApplicationGateway'
        required: false
        default: false
        type: boolean
      appGWcount:
        description: 'appGWcount'
        required: false
        type: number
      appGWsku:
        description: 'appGWsku'
        required: false
        type: string
      azureKeyvaultSecretsProvider:
        description: 'azureKeyvaultSecretsProvider'
        required: false
        default: false
        type: boolean
      createKV:
        description: 'createKV'
        required: false
        default: false
        type: boolean
      kvOfficerRolePrincipalId:
        description: 'kvOfficerRolePrincipalId'
        required: false
        type: string
      monitor:
        description: 'monitor'
        required: false
        type: string
      ingress:
        description: 'ingress'
        required: false
        type: string
      certEmail:
        description: 'certEmail'
        required: false
        type: string
      enableMonitorIngress:
        description: 'enableMonitorIngress'
        required: false
        type: boolean
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      USER_OBJECT_ID:
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "${{ toJSON(inputs) }}"
      - name: Echo2
        run: |
          echo "${{ toJSON(inputs.*) }}"
